### ISSUE TITLE
Inquiry Regarding Computational Resources for Model Training

### ISSUE THREAD

**Issue by hezhiyang2000** [fmerizzi/ERA5-to-CERRA-via-Diffusion-Models#1]
Hello fmerizzi,

I hope this message finds you well. I am writing to inquire about the computational resources involved in training the final diffusion model, which has been of great interest to me and the community. Understanding the hardware requirements and time commitment is crucial for those of us considering replicating or building upon your work, especially in environments with limited resources.

Could you please provide detailed information on the following aspects of your training process?

1. **GPU Usage:**
   - What type and how many GPUs were used for training?
   - Was there any specific configuration or optimization performed to maximize GPU utilization?

2. **Training Duration:**
   - Approximately how long did it take to train the model for 200 epochs?
   - If possible, could you share the time per epoch and whether this duration was consistent across all epochs?

Your insights into these questions would greatly benefit the community by providing a clearer understanding of the model’s training requirements and facilitating more efficient resource planning for similar projects.

Thank you for your time and consideration. I look forward to your response and any additional information you can share.

Best regards

**Comment by fmerizzi** [comment]
Hello, 

The training was executed on a single RTX 4000 gpu. 
No additional optimization was performed outside the provided code. 

The model is trained for approximately 30 hours. 
The time per epoch was around 7 minutes, consistent across all epochs.
