### ISSUE TITLE
ValueError while fine tuning the diffusion model

### ISSUE THREAD

**Issue by mvallesf** [fmerizzi/ERA5-to-CERRA-via-Diffusion-Models#2]
While trying to fine tuning the model I get this error:

_ValueError: Layer "residual_unet" expects 2 input(s), but it received 1 input tensors. Inputs received: [<tf.Tensor 'IteratorGetNext:0' shape=(None, None, None, None) dtype=float32>]_

I only get it when I make some of the layers not trainable (I have made tests and even with just one random no trainable layer happens), but if I just retrain everything (doing exactly the same) I don't get the error and everything works fine.

**Comment by fmerizzi** [comment]
The residual U-net expects both a positional embedding and conditioning information, be sure to provide both
