### ISSUE TITLE
Code for IGRAv2 Validation

### ISSUE THREAD

**Issue by shiemn** [fmerizzi/ERA5-to-CERRA-via-Diffusion-Models#3]
Hei Hei,

I'm currently trying to reproduce the validation procedure on IGRAv2, using the description from this repo and the paper, but struggle to achieve the same results (even on the baseline CERRA/ERA scores).

Would it be possible to provide the code used for your validation on IGRA?

Thank you for your help :)

Best regards
Simon

**Comment by fmerizzi** [comment]
Hello Simon,

Yes, we can release the code for that part as well, I should be able to publish it in a matter of days. 

Best,
Fabio

**Comment by fmerizzi** [comment]
I have now committed the code for the validation procedure
